### ISSUE TITLE
Add top level marks that decorate whole `impl` sections

### ISSUE THREAD

**Issue by mfornet** [aurora-is-near/near-plugins#3]
Right now `#[pause]` and `#[only]` can only be used at the level function. In some implementations, different `impl` sections are grouped with different access requirements but similar for every function in the same `impl`. For those cases, it makes sense to have current markers to work at a top level.

**Comment by vzctl** [comment]
Closing this issue as non-relevant anymore. Please re-open if needed  /cc @birchmd @mooori

**Comment by mooori** [comment]
Just for reference: The motivation for closing it is given in the conversation of #109 (which was a copy of this issue here).
