### ISSUE TITLE
Add examples utilizing plugins

### ISSUE THREAD

**Issue by sept-en** [aurora-is-near/near-plugins#30]

**Comment by mooori** [comment]
For the Acl plugin, [this test contract](https://github.com/aurora-is-near/near-plugins/blob/a55c3a076d019af2202c295c4de4d0027dfc0c69/near-plugins/tests/contracts/access_controllable/src/lib.rs) can also serve as example. Probably we should mention it in the README.

**Comment by sept-en** [comment]
@mooori Olha is about to finish adding several examples there, the PR will be created soon. The issue is just to have an appropriate one matched to the PR.
