### ISSUE TITLE
Improve plugins examples documentation

### ISSUE THREAD

**Issue by sept-en** [aurora-is-near/near-plugins#31]
The existing examples lack information on what should be tested after the new functionality is added, what should be an initiating/deployment workflow, etc. Also, it would be good to provide suggestions on best practices on use cases of each plugin and when-not-to-use.

**Comment by mfornet** [comment]
Ironically this issue in itself requires to be expanded. What documentation are you expecting? examples, function docs, macros docs, autogenerated docs?

**Comment by sept-en** [comment]
@mfornet yes, indeed it was not there:) updated.
